cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url('contextbacket/$', views.contextbacket, name='contextbacket'),
]
app_name = 'cart'

data/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.second,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/product/$',
        views.product,
        name='product'),

    url(r'^(?P<category_slug>[-\w]+)/(?P<firstcategory_slug>[-\w]+)/(?P<secondcategory_slug>[-\w]+)/$',
        views.second,
        name='second'),
    url(r'^(?P<category_slug>[-\w]+)/first/$',
        views.first,
        name='first'),

]
app_name = 'shop'

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('data.data_urls')),
    path(r'cart/', include('cart.urls', namespace='cart')),
    path(r'calculator/', include('calculator.urls', namespace='calculator')),
    path('test/', include('data.urls', namespace='shop')),
    path(r'orders/', include('orders.urls', namespace='orders')),
    path(r'log/',include('loginlogout.log_urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

data/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.safestring import mark_safe
import django_filters

User = get_user_model()





class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
    def get_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Sorter(models.Model):
    sorter = models.ForeignKey(Category, related_name='sorter', on_delete=models.CASCADE, null=True, blank=True )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Фильтры'
        verbose_name_plural = 'Фильтры'

    def __str__(self):
        return self.name


class FirstCategory(models.Model):
    firstcategory = models.ForeignKey(Category, related_name='firstproducts', on_delete=models.CASCADE, )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Первая Категория'
        verbose_name_plural = 'Первая Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:first',
                       args=[self.slug])

class SecondCategory(models.Model):
    secondcategory = models.ForeignKey(FirstCategory, related_name='secondproducts', on_delete=models.CASCADE, )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Вторая Категория'
        verbose_name_plural = 'Вторая Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:second',
                       args=[self.secondcategory.firstcategory.slug, self.secondcategory.slug,self.slug])


class Product(models.Model):

    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE,)
    thirdcategory = models.ForeignKey(SecondCategory, related_name='thirdproducts', on_delete=models.CASCADE, null=True, blank=True )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукты'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='icontains', label='Search by name of product')
    price = django_filters.RangeFilter()

    class Meta:
        model = Product
        fields = ['price','name']




class Common(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название раздела', help_text='название основного раздела')
    slug = models.SlugField(null=True, unique=True, blank=True, verbose_name='URL адрес', help_text='название url адреса')
    mobile = models.BooleanField(verbose_name='Мобильная версия', help_text='поставить галочку если нужно в мобильной версии')

    class Meta:
        abstract = True

class Mainbar(Common):
    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Основное меню"
    def __str__(self):
        return self.name

class Subbar(Common):
    class Meta:
        verbose_name = "Подраздел"
        verbose_name_plural = "Подменю"

    subname = models.ForeignKey(Mainbar, on_delete=models.CASCADE, related_name="subbar", null=True, blank=True)
    def __str__(self):
        return self.name






class Post (models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

class Video(models.Model):
    class Meta:
        verbose_name = "Товары"
        verbose_name_plural = "Много товаров"

    name_video = models.CharField(max_length=100, null=True, blank=True, verbose_name='товары ччч', help_text='просто текст про товары')
    url_video = models.URLField(null=True)
    di_video = models.TextField(null=True)
    date_video = models.DateTimeField(auto_now_add=True, null=True)
    likes_video = models.PositiveIntegerField(default=0)
    slug = models.SlugField(null=True, unique=True)


    @property
    def videoplay(self):
        return mark_safe('<iframe width="100" height="50" src="' + self.url_video + '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

    def __str__(self):
        return self.name_video

class Comment(models.Model):
    class Meta:
        db_table = "Комментарии"
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    text = models.TextField()
    likes = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

data/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Mainbar, Category, Product, Sorter, FirstCategory, SecondCategory, ProductFilter
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.template.context_processors import csrf
from .forms import EmailPostForm
from django.core.mail import send_mail



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Product, id=post_id)
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.name)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.name, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'ugeopolimer@gmail.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})




def shop(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'index.html', response)

def test(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'test.html', response)

def product_list(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        try:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        except:
            pass
    return render(request,
                  'shop/product/testlist.html',
                  {'category': category,'bar':bar,'mobar':mobar,
                   'categories': categories,'sorter':sorter,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def product(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/product.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def first(request, category_slug=None):
    category = None
    cart_product_form = CartAddProductForm()
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    if category_slug:
        category = get_object_or_404(FirstCategory, slug=category_slug)
        second = SecondCategory.objects.filter(secondcategory=category)
        products = Product.objects.filter(available=True).filter(thirdcategory=second[0])
        for item in second:
            products |= Product.objects.filter(available=True).filter(thirdcategory=item)

    return render(request,
                  'shop/product/first.html',
                  {'category': category, 'cart_product_form': cart_product_form,
                   'categories': categories,
                   'firstproducts': products,
                  'sorter':sorter})



def second(request, category_slug=None, firstcategory_slug= None, secondcategory_slug=None):
    bar = Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None

    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    secondcategories = SecondCategory.objects.all()
    # if firstcategory_slug:
    #     secondcategories = SecondCategory.objects.filter(secondcategory=get_object_or_404(FirstCategory, slug=firstcategory_slug))
    #     print(secondcategories)

    if secondcategory_slug:
        category = get_object_or_404(SecondCategory, slug=secondcategory_slug)
        products = products.filter(thirdcategory=category)
        category = get_object_or_404(Category, slug=category_slug)
    else:
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
    firstcategories=FirstCategory.objects.filter(firstcategory=get_object_or_404(Category, slug=category_slug))
    # page = request.GET.get('page')

    t=3
    fproduct = ProductFilter(request.GET, queryset=products)
    paginator = Paginator(fproduct.qs, t)  # 6 posts in each page
    page = request.GET.get('page')
    filterrequest=request.GET
    filterrequest._mutable = True
    print(filterrequest)

    if page:
        del filterrequest['page']
        lqty = int(page)*t
        uqty = int(page) * t+t
    else:
        lqty=1
        uqty=1*t

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    print(filterrequest.get('lqty'))
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category, 'bar': bar, 'mobar': mobar, 'page': page, 'filter': fproduct,'filterrequest':filterrequest,'lqty':lqty, 'uqty' :uqty,
                   'categories': categories, 'sorter': sorter, 'firstcategories':firstcategories,  'opencategory':firstcategory_slug,
                   'products': products})



def shop_sidebar(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)


    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    f = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category,'bar':bar,'mobar':mobar,'page': page, 'filter': f,
                   'categories': categories,'sorter':sorter,
                   'products': products})

data/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

data/templates/shop/product/first.html
{% load static %}


        <div class="product-tab-list">
            <!-- Nav tabs -->
            <ul class="tab-style" >
                {% for sorter in sorter %}
                 {% if forloop.counter  == 1 %}
                <li class="active"> {%else%} <li>{% endif %}
                    <a href="#{{ sorter.slug }}" data-toggle="tab">
                        <div class="tab-menu-text">
                            <h4>{{ sorter.name }}</h4>
                        </div>
                    </a>
                </li>
                 {% endfor %}
            </ul>

        </div>

         <div class="tab-content another-product-style jump" >
            <div class="tab-pane active" id="latest">
                 <div class="row">
                    <div class="product-slider-active owl-carousel" role="listbox">
                         {% for product in firstproducts %}
                        <div class="col-md-4 single__pro col-lg-4 cat--1 col-sm-4 col-xs-12" >
                            <div class="product">
                                        <div class="product__inner">
                                            <div class="pro__thumb">

                                                    <img src="{% if product.image %}{{ product.image.url }}{% else %}
                                                    {% static 'plater/images/new.jpg' %}{% endif %}" alt='{{product.name}}'>

                                            </div>
                                            <div class="product__hover__info">
                                                <ul class="product__action">

                                                    <li><a data-toggle="modal"id= "{{ product.name }}" data-target="#productModal" title="Quick View" class="quick-view modal-view detail-link" href="#"><span class="ti-plus"></span></a></li>
                                                    <li><a ><span class="ti-shopping-cart"></span>

                                                    </a>
                                                    </li>
                                                    <li><a title="Wishlist" ><span class="ti-heart"></span></a></li>
                                                </ul>
                                            </div>
                                        </div>
                                                <div class="product__details"  >

                                                    <h2 title= "{{ product.name }}"><a href="{{ product.get_absolute_url }}">{{ product.name }}</a></h2>
                                                    <ul class="product__price">
                                                        <li class="old__price">$16.00</li>
                                                        <li class="new__price"> ${{ product.price }}</li>
                                                    </ul>
                                                </div>
                                                    <div class="product-quantity">
                                                         <form id="{% url "cart:cart_add" product.id %}" title="AddLine" method="post" id='{% url "cart:cart_add" product.id %}'>
                                                             {{ cart_product_form }}
                                                            {% csrf_token %}
                                                            <input  id = 'AddLine' value="Add to cart" class="btn btn-primary solid blank">
                                                         </form>
                                                     </div>


                            </div>
                        </div>{% endfor %}


                    </div>
                 </div>
            </div>
         </div>
<script>



</script>

data/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div id="sidebar">
        <h3>Categories</h3>
        <ul>
            <li {% if not category %}class="selected"{% endif %}>
                <a href="{% url "shop:product_list" %}">All</a>
            </li>
            {% for c in categories %}
                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
    <div id="main" class="product-list">
        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
        {% for product in products %}
            <div class="item">
                <a href="{{ product.get_absolute_url }}">
                    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
                </a>
                <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
                ${{ product.price }}
            </div>
        {% endfor %}
    </div>
{% endblock %}

data/templates/shop/product/product.html
{% load static %}
    <div class="product-images">
        <div class="main-image images">
            <div class="product-detail">
                <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
            </div>
         </div>
    </div>

    <div class="product-info">

    <h1>{{ product.name }}</h1>
     <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <div class="rating__and__review">
            <ul class="rating">
                <li><span class="ti-star"></span></li>
                <li><span class="ti-star"></span></li>
                <li><span class="ti-star"></span></li>
                <li><span class="ti-star"></span></li>
                <li><span class="ti-star"></span></li>
            </ul>
            <div class="review">
                <a href="#">4 customer reviews</a>
            </div>
        </div>
         <div title="CartBacket" class="cart">
              <h1>Your shopping cart</h1>
                    {% with total_items=cart|length %}
                        {% if cart|length > 0 %}
                            Your cart:
                            <a href="{% url "cart:cart_detail" %}">
                                {{ total_items }} item{{ total_items|pluralize }},
                                ${{ cart.get_total_price }}
                            </a>
                        {% else %}
                            Your cart is empty.
                        {% endif %}
                    {% endwith %}
         </div>
        <div class="price-box-3">
            <div class="s-price-box">
                <span class="new-price">${{ product.price }}</span>
                <span class="old-price">$45.00</span>
            </div>
        </div>
        <div class="quick-desc">
            {{ product.description|linebreaks }}
        </div>
         <div class="addtocart-btn">
             <form  title='AddToChart' method="post" id='{% url "cart:cart_add" product.id %}'>
                {{ cart_product_form }}
                {% csrf_token %}
                <input id= 'Add_to_chart' value="Add to cart" class="btn btn-primary solid blank">
             </form>
        </div>
    </div>

<script>
  $("#Add_to_chart").click( function() {
   let arr = {csrfmiddlewaretoken:document.getElementsByName('csrfmiddlewaretoken')[0].value}

    $(":input[title='AddToCart']").each(function(){
    arr[$(this).attr('name')]=$(this).val();
    })
            var href = $('form[title=AddToChart]').attr('id');
            console.log(arr);
            $.ajax({url:href,
                   type: 'post',
                    data: arr,

                    success: function (data) {

                    $.ajax({url:'/cart/contextbacket/',
                    success: function (data) {

                         $("div[title='CartBacket']").html(data)
                    }});

                    }});

        })

  $("#Add_to_chart").click( function() {

         })

</script>

<!--action="{% url "cart:cart_add" product.id %}" type="submit" alert('Вы добавили товар');-->

data/templates/shop/product/testdetail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

data/templates/shop/product/testlist.html
{% extends "test.html" %}
{% load static %}
 <script src="{% static 'plaster/js/vendor/jquery-1.12.0.min.js' %}"></script>
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
        <div class='category-heading'>
          <h3>  <a href='{% url "shop:product_list" %}'>Browse Categories</a></h3>
        </div>
         <div class="category-menu-list">
            <ul>
                {% for c in categories %}
                <li><a href="{{ c.get_absolute_url }}"><img alt="" src="{% static 'plaster/images/icons/thum2.png' %}"> {{ c.name }}<i class="zmdi zmdi-chevron-right"></i></a>
                    <div class="category-menu-dropdown">
                        <div title='category'>
                            {% for first in c.firstproducts.all %}
                            <div title = 'element' class="category-part-1 category-common mb--30">

                                <h4 class="categories-subtitle"> {{ first.name}}</h4>
                               <ul>
                                      {% for second in first.secondproducts.all %}
                                    <li><a href="{{ second.get_absolute_url }}">{{ second.name }}</a></li>

                                    {% endfor %}
                                </ul>

                            </div>


                            {% endfor %}

                        </div>
                    </div>
                </li>
                {% endfor %}
            </ul>
         </div>
{% endblock %}