cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url('contextbacket/$', views.contextbacket, name='contextbacket'),
]
app_name = 'cart'

data/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.second,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/product/$',
        views.product,
        name='product'),

    url(r'^(?P<category_slug>[-\w]+)/(?P<firstcategory_slug>[-\w]+)/(?P<secondcategory_slug>[-\w]+)/$',
        views.second,
        name='second'),
    url(r'^(?P<category_slug>[-\w]+)/first/$',
        views.first,
        name='first'),

]
app_name = 'shop'

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

app_name = 'orders'

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('data.data_urls')),
    path(r'cart/', include('cart.urls', namespace='cart')),
    path(r'calculator/', include('calculator.urls', namespace='calculator')),
    path('test/', include('data.urls', namespace='shop')),
    path(r'orders/', include('orders.urls', namespace='orders')),
    path(r'log/',include('loginlogout.log_urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

data/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse
from django.utils.safestring import mark_safe
import django_filters

User = get_user_model()





class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])
    def get_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])


class Sorter(models.Model):
    sorter = models.ForeignKey(Category, related_name='sorter', on_delete=models.CASCADE, null=True, blank=True )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Фильтры'
        verbose_name_plural = 'Фильтры'

    def __str__(self):
        return self.name


class FirstCategory(models.Model):
    firstcategory = models.ForeignKey(Category, related_name='firstproducts', on_delete=models.CASCADE, )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Первая Категория'
        verbose_name_plural = 'Первая Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:first',
                       args=[self.slug])

class SecondCategory(models.Model):
    secondcategory = models.ForeignKey(FirstCategory, related_name='secondproducts', on_delete=models.CASCADE, )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)


    class Meta:
        ordering = ('name',)
        verbose_name = 'Вторая Категория'
        verbose_name_plural = 'Вторая Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:second',
                       args=[self.secondcategory.firstcategory.slug, self.secondcategory.slug,self.slug])


class Product(models.Model):

    category = models.ForeignKey(Category, related_name='products',on_delete=models.CASCADE,)
    thirdcategory = models.ForeignKey(SecondCategory, related_name='thirdproducts', on_delete=models.CASCADE, null=True, blank=True )
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    stock = models.PositiveIntegerField()
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Продукты'
        verbose_name_plural = 'Продукты'
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

class ProductFilter(django_filters.FilterSet):
    name = django_filters.CharFilter(lookup_expr='icontains', label='Search by name of product')
    price = django_filters.RangeFilter()

    class Meta:
        model = Product
        fields = ['price','name']




class Common(models.Model):
    name = models.CharField(max_length=100, null=True, blank=True, verbose_name='Название раздела', help_text='название основного раздела')
    slug = models.SlugField(null=True, unique=True, blank=True, verbose_name='URL адрес', help_text='название url адреса')
    mobile = models.BooleanField(verbose_name='Мобильная версия', help_text='поставить галочку если нужно в мобильной версии')

    class Meta:
        abstract = True

class Mainbar(Common):
    class Meta:
        verbose_name = "Раздел"
        verbose_name_plural = "Основное меню"
    def __str__(self):
        return self.name

class Subbar(Common):
    class Meta:
        verbose_name = "Подраздел"
        verbose_name_plural = "Подменю"

    subname = models.ForeignKey(Mainbar, on_delete=models.CASCADE, related_name="subbar", null=True, blank=True)
    def __str__(self):
        return self.name






class Post (models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.title

class Video(models.Model):
    class Meta:
        verbose_name = "Товары"
        verbose_name_plural = "Много товаров"

    name_video = models.CharField(max_length=100, null=True, blank=True, verbose_name='товары ччч', help_text='просто текст про товары')
    url_video = models.URLField(null=True)
    di_video = models.TextField(null=True)
    date_video = models.DateTimeField(auto_now_add=True, null=True)
    likes_video = models.PositiveIntegerField(default=0)
    slug = models.SlugField(null=True, unique=True)


    @property
    def videoplay(self):
        return mark_safe('<iframe width="100" height="50" src="' + self.url_video + '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>')

    def __str__(self):
        return self.name_video

class Comment(models.Model):
    class Meta:
        db_table = "Комментарии"
        verbose_name = "Комментарий"
        verbose_name_plural = "Комментарии"

    text = models.TextField()
    likes = models.PositiveIntegerField()
    date = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    video = models.ForeignKey(Video, on_delete=models.CASCADE)

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, widget=forms.Select(attrs={'title': 'AddToCart', 'class':'product-quantity'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

data/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from data.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    print("text")
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    print(request)
    print(form)
    print(product)
    if form.is_valid():
        print("text1")
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
        print(cart)
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)

    return render(request, 'cart.html', {'cart': cart})

def contextbacket(request):

    return render(request, 'contextbacket.html')

data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Mainbar, Category, Product, Sorter, FirstCategory, SecondCategory, ProductFilter
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.template.context_processors import csrf
from .forms import EmailPostForm
from django.core.mail import send_mail



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Product, id=post_id)
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.name)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.name, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'ugeopolimer@gmail.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})




def shop(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'index.html', response)

def test(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'test.html', response)

def product_list(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        try:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        except:
            pass
    return render(request,
                  'shop/product/testlist.html',
                  {'category': category,'bar':bar,'mobar':mobar,
                   'categories': categories,'sorter':sorter,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def product(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/product.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def first(request, category_slug=None):
    category = None
    cart_product_form = CartAddProductForm()
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    if category_slug:
        category = get_object_or_404(FirstCategory, slug=category_slug)
        second = SecondCategory.objects.filter(secondcategory=category)
        products = Product.objects.filter(available=True).filter(thirdcategory=second[0])
        for item in second:
            products |= Product.objects.filter(available=True).filter(thirdcategory=item)

    return render(request,
                  'shop/product/first.html',
                  {'category': category, 'cart_product_form': cart_product_form,
                   'categories': categories,
                   'firstproducts': products,
                  'sorter':sorter})



def second(request, category_slug=None, firstcategory_slug= None, secondcategory_slug=None):
    bar = Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None

    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    secondcategories = SecondCategory.objects.all()
    # if firstcategory_slug:
    #     secondcategories = SecondCategory.objects.filter(secondcategory=get_object_or_404(FirstCategory, slug=firstcategory_slug))
    #     print(secondcategories)

    if secondcategory_slug:
        category = get_object_or_404(SecondCategory, slug=secondcategory_slug)
        products = products.filter(thirdcategory=category)
        category = get_object_or_404(Category, slug=category_slug)
    else:
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
    firstcategories=FirstCategory.objects.filter(firstcategory=get_object_or_404(Category, slug=category_slug))
    # page = request.GET.get('page')

    t=3
    fproduct = ProductFilter(request.GET, queryset=products)
    paginator = Paginator(fproduct.qs, t)  # 6 posts in each page
    page = request.GET.get('page')
    filterrequest=request.GET
    filterrequest._mutable = True
    print(filterrequest)

    if page:
        del filterrequest['page']
        lqty = int(page)*t
        uqty = int(page) * t+t
    else:
        lqty=1
        uqty=1*t

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    print(filterrequest.get('lqty'))
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category, 'bar': bar, 'mobar': mobar, 'page': page, 'filter': fproduct,'filterrequest':filterrequest,'lqty':lqty, 'uqty' :uqty,
                   'categories': categories, 'sorter': sorter, 'firstcategories':firstcategories,  'opencategory':firstcategory_slug,
                   'products': products})



def shop_sidebar(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)


    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    f = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category,'bar':bar,'mobar':mobar,'page': page, 'filter': f,
                   'categories': categories,'sorter':sorter,
                   'products': products})

data/templates/cart.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Your shopping cart
{% endblock %}
{% block content %}
    <h1>Your shopping cart</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Image</th>
            <th>Product</th>
            <th>Quantity</th>
            <th>Remove</th>
            <th>Unit price</th>
            <th>Price</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product}}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id%}">Remove</a></td>
                    <td><a href="{% url "shop:post_share" product.id %}">My shop</a>/td>
                    <td class="num">${{ item.price }}</td>
                    <td class="num">${{ item.total_price }}</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4"></td>
            <td class="num">${{ cart.get_total_price }}</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Continue shopping</a>
        <a href="{% url "orders:order_create" %}" class="button">
        Checkout
        </a>
    </p>
{% endblock %}

data/templates/contextbacket.html
{% load static %}
 <h1>Your shopping cart</h1>
{% with total_items=cart|length %}
    {% if cart|length > 0 %}
        Your cart:
        <a href="{% url "cart:cart_detail" %}">
            {{ total_items }} item{{ total_items|pluralize }},
            ${{ cart.get_total_price }}
        </a>
    {% else %}
        Your cart is empty.
    {% endif %}
{% endwith %}

data/templates/head.html
<!doctype html>
{% load static %}
<html class="no-js" lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Tmart-Minimalist eCommerce HTML5 Template</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Place favicon.ico in the root directory -->
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'plaster/images/favicon.ico' %}">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <!-- All css files are included here. -->
    <!-- Bootstrap fremwork main css -->
    <link rel="stylesheet" href="{% static 'plaster/css/bootstrap.min.css' %}">
    <!-- Owl Carousel main css -->
    <link rel="stylesheet" href="{% static 'plaster/css/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'plaster/css/owl.theme.default.min.css' %}">
    <!-- This core.css file contents all plugings css file. -->
    <link rel="stylesheet" href="{% static 'plaster/css/core.css' %}">
    <!-- Theme shortcodes/elements style -->
    <link rel="stylesheet" href="{% static 'plaster/css/shortcode/shortcodes.css' %}">
    <!-- Theme main style -->
    <link rel="stylesheet" href="{% static 'plaster/style.css' %}">
    <!-- Responsive css -->
    <link rel="stylesheet" href="{% static 'plaster/css/responsive.css' %}">
    <!-- User style -->
    <link rel="stylesheet" href="{% static 'plaster/css/custom.css' %}">


    <!-- Modernizr JS -->
    <script src="{% static 'plaster/js/vendor/modernizr-2.8.3.min.js' %}"></script>

    <script src="{% static 'plaster/js/vendor/jquery-1.12.0.min.js' %}"></script>
</head>

<body>
    {% block index %}
    {% endblock %}
    <!-- END QUICKVIEW PRODUCT -->
    <!-- Placed js at the end of the document so the pages load faster -->

    <!-- jquery latest version -->

    <!-- Bootstrap framework js -->
    <script src="{% static 'plaster/js/bootstrap.min.js' %}"></script>
    <!-- All js plugins included in this file. -->
    <script src="{% static 'plaster/js/plugins.js' %}"></script>
    <script src="{% static 'plaster/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'plaster/js/owl.carousel.min.js' %}"></script>
    <!-- Waypoints.min.js. -->
    <script src="{% static 'plaster/js/waypoints.min.js' %}"></script>
    <!-- Main js file that contents all jQuery plugins activation. -->
    <script src="{% static 'plaster/js/main.js' %}"></script>

</body>
</html>

data/templates/header.html
{% load static%}
        <!-- Start Header Style -->
        <header id="header" class="htc-header header--3 bg__white">
            <!-- Start Mainmenu Area -->
            <div id="sticky-header-with-topbar" class="mainmenu__area sticky__header">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2 col-lg-2 col-sm-3 col-xs-3">
                            <div class="logo">
                                <a href="index.html">
                                    <img src="{% static 'plaster/images/logo/logo.png' %}" alt="logo">
                                </a>
                            </div>
                        </div>
                        <!-- Start MAinmenu Ares -->
                        <div title="CartBacket" class="cart">
                            {% with total_items=cart|length %}
                                {% if cart|length > 0 %}
                                    Your cart:
                                    <a href="{% url "cart:cart_detail" %}">
                                        {{ total_items }} item{{ total_items|pluralize }},
                                        ${{ cart.get_total_price }}
                                    </a>
                                {% else %}
                                    Your cart is empty.
                                {% endif %}
                            {% endwith %}
                        </div>

                        <div class="col-md-8 col-lg-8 col-sm-6 col-xs-6">
                            <nav class="mainmenu__nav hidden-xs hidden-sm">
                                <ul class="main__menu">
                                    {% for section in bar%}
                                    <li class="drop"><a href="/{{ section.slug }}">{{ section.name }}</a>
                                        <ul class="dropdown">
                                            {% for subsection in section.subbar.all %}
                                            <li><a href="/{{ section.slug }}/{{ subsection.slug }}">{{ subsection.name }}</a></li>{% endfor %}
                                        </ul>
                                    </li>{% endfor %}
                                </ul>
                            </nav>
                            <div class="mobile-menu clearfix visible-xs visible-sm">
                                <nav id="mobile_dropdown">
                                    <ul>
                                        {% for section in mobar %}
                                        <li><a href="/{{ section.slug }}">{{ section.name }}</a>
                                            <ul>{% for subsection in section.subbar.all %}
                                                <li><a href="/{{ section.slug }}/{{ subsection.slug }}">{{ subsection.name }}</a></li>{% endfor %}
                                            </ul>
                                        </li>{% endfor %}
                                    </ul>
                                </nav>
                            </div>
                        </div>
                        <!-- End MAinmenu Ares -->
                        <div class="col-md-2 col-sm-4 col-xs-3">
                            <ul class="menu-extra">
                                <li class="search search__open hidden-xs"><span class="ti-search"></span></li>
                                <li><a href="/log/"><span class="ti-user"></span></a></li>
                                <li class="cart__menu"><span class="ti-shopping-cart"></span></li>
                                <li class="toggle__menu hidden-xs hidden-sm"><span class="ti-menu"></span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="mobile-menu-area"></div>
                </div>
            </div>
            <!-- End Mainmenu Area -->
        </header>
        <!-- End Header Style -->

data/templates/pagination.html
{% load shop_tags %}
{% total_products_search filter as add_users_flag %}
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}&{{ filterrequest.urlencode }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}.
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}&{{ filterrequest.urlencode }}">Next</a>
        {% endif %}
    </span>
    <div class="shp__pro__show">
        <span> Showing {{ lqty }} -  {% if add_users_flag > uqty %} {{ uqty }} {% else %} {% total_products_search filter %} {% endif %} of {% total_products_search filter %}
            results {{ add_users_flag }} </span>
    </div>
</div>