calculator/urls.py
from django.conf.urls import url
from . import views
from .views import FORMS


urlpatterns = [
    url(r'^$', views.calculator, name='calculator'),
    url(r'^remove/(?P<id>\w+)/(?P<element_id>\d+)/$', views.calculator_remove, name='calculator_remove'),
    url(r'^addstudent/$', views.AddStudentWizard.as_view(FORMS), name='addstudent'),
    url(r'^test/$',views.test),
    url(r'^add/$', views.HomePage.as_view()),


]
app_name = 'calculator'

cart/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
    url('contextbacket/$', views.contextbacket, name='contextbacket'),
]
app_name = 'cart'

data/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^(?P<post_id>\d+)/share/$', views.post_share, name='post_share'),
    url(r'^$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.second,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/product/$',
        views.product,
        name='product'),

    url(r'^(?P<category_slug>[-\w]+)/(?P<firstcategory_slug>[-\w]+)/(?P<secondcategory_slug>[-\w]+)/$',
        views.second,
        name='second'),
    url(r'^(?P<category_slug>[-\w]+)/first/$',
        views.first,
        name='first'),

]
app_name = 'shop'

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('shop/', include('data.data_urls')),
    path(r'cart/', include('cart.urls', namespace='cart')),
    path(r'calculator/', include('calculator.urls', namespace='calculator')),
    path('test/', include('data.urls', namespace='shop')),
    path(r'orders/', include('orders.urls', namespace='orders')),
    path(r'log/',include('loginlogout.log_urls')),




]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

calculator/forms.py
from django import forms
from .models import Element

PRODUCT_QUANTITY_CHOICES = Element.objects.all()


class ElementsForm(forms.Form):
    quantity = forms.ModelChoiceField(queryset = PRODUCT_QUANTITY_CHOICES)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

class ParametersForm(forms.Form):
    num1 = forms.IntegerField(required=False, initial="0")
    num2 = forms.IntegerField(required=False, initial="0")

class HomeForm(forms.Form):
    num1 = forms.IntegerField(required=False)
    num2 = forms.IntegerField(required=False)

data/forms.py
from django import forms


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)

calculator/views.py
from __future__ import unicode_literals
from django.views.generic import TemplateView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import HomeForm, ElementsForm, ParametersForm
from .models import Job, Element
from .calculator import Calculator
from data.models import Product
from formtools.wizard.views import SessionWizardView


from io import StringIO,BytesIO
from xhtml2pdf import pisa
from django.template.loader import get_template
from django.template import Context
from django.http import HttpResponse
from cgi import escape



def render_to_pdf(template_src, context_dict):
    print(template_src,context_dict)
    template = get_template(template_src)
    context = context_dict
    html  = template.render(context)
    result = BytesIO()

    pdf = pisa.pisaDocument(BytesIO(html.encode("utf-16")), result)
    if not pdf.err:
        return HttpResponse(result.getvalue(), content_type='application/pdf')
    return HttpResponse('We had some errors<pre>%s</pre>' % escape(html))



FORMS = [
      ("element", ElementsForm),
      ("parameters", ParametersForm)
  ]
TEMPLATES = {
      "element" : "calculator/student.html",
      "parameters" : "calculator/contract.html"
  }

class AddStudentWizard(SessionWizardView):
    def get_template_names(self):
        return [TEMPLATES[self.steps.current]]

    def get_context_data(self, form, **kwargs):
        print(form)
        context = super(AddStudentWizard, self).get_context_data(form=form, **kwargs)
        if self.steps.current == 'parameters':
            context.update({'ok': 'True'})
        return context

    def done(self, form_list, **kwargs):
        print(form_list)
        # student_form = form_list[0].cleaned_data
        # contract_form = form_list[1].cleaned_data
        # s = Student.objects.create(
        #     sex=student_form['sex'],
        #     citizenship=student_form['citizenship'],
        #     doc=student_form['doc'],
        #     student_document_type=student_form['student_document_type'],
        #     parent_document_type=student_form['parent_document_type']
        # )
        # f = FioChange.objects.create(
        #     student=s,
        #     event_date=student_form['event_date'],
        #     fio=student_form['fio']
        # )
        # c = Contract.objects.create(
        #     student=s,
        #     number=contract_form['number'],
        #     student_home_phone=contract_form['phone']
        # )
        return HttpResponseRedirect(reverse('liststudent'))



# Create your views here.
class HomePage(TemplateView):
    template_name = 'calculator/home.html'

    def get(self, request, *args, **kwargs):
        form = HomeForm()
        return render(request,self.template_name, {'form':form})

    def post(self,request):
        form = HomeForm(request.POST)
        if form.is_valid():
            text = form.cleaned_data['num1']
            text2 = form.cleaned_data['num2']
            if 'add' in request.POST:
                result = text + text2
            elif 'sub' in request.POST:
                result = text - text2
            elif 'mul' in request.POST:
                result = text * text2
            elif 'div' in request.POST:
                result = text / text2

            form = HomeForm()
            #return redirect ('home:home')

        args = {'form': form , 'result': result}
        return render(request, self.template_name, args )


def calculator(request):
    print("1")

    calculator = Calculator(request)


    if request.method == 'GET':
        Parameters = ParametersForm(request.GET)
        Elements = ElementsForm(request.GET)
        if (request.GET.get('print_btn')) and Parameters.is_valid():

            numbers = Parameters.cleaned_data
            for i in numbers:
                if numbers[i]==None:
                    numbers[i]=0

            job = Job.objects.filter(process=request.GET.get('quantity'))
            element = Element.objects.filter(id=request.GET.get('quantity'))

            for i in job:
                calculator.add(job=i, num1=numbers['num1'], num2=numbers['num2'], element=element[0].name)
            return render(request, 'calculator/calculator.html',
                          {'ElementsForm': Elements, 'ParametersForm': Parameters, 'calculator': calculator})
        elif Elements.is_valid():
            cd = Elements.cleaned_data
            calculator.element(cd['quantity'])
            return render(request, 'calculator/calculator.html',
                  {'ElementsForm': Elements, 'ParametersForm':Parameters, 'calculator':calculator } )
        else:
            Elements = ElementsForm()


    else:
        Elements = ElementsForm()
        Parameters=ParametersForm()



    return render(request, 'calculator/calculator.html',
                  {'ElementsForm': Elements, 'ParametersForm':Parameters, 'calculator':calculator})

def calculator_remove(request, id, element_id):
    if id=='main':
        calculator= Calculator(request)
        elements = get_object_or_404(Element, id=element_id)
        calculator.mainremove(elements.name)
    elif id=='process':
        calculator= Calculator(request)
        process = get_object_or_404(Job, id=element_id)
        calculator.processremove(process.name)
    elif id=='product':
        calculator= Calculator(request)
        product = get_object_or_404(Product, id=element_id)
        calculator.productremove(product.name)

    return redirect('calculator:calculator')
from io import BytesIO
from reportlab.pdfgen import canvas
from django.http import HttpResponse

import pdfcrowd

def test(request):
    calculator = Calculator(request)
    Elements = ElementsForm()
    Parameters = ParametersForm()
    api = pdfcrowd.HtmlToPdfClient("evgeniy111", "9fcddf22e94642a39acf43b932382beb")
    api.convertUrlToFile('http://uretekbelarus.com', '/Users/apple/PycharmProjects/Uretekweb/uretek/static/constra-free/themes/example.pdf')
    print(api)
    return render_to_pdf(
        'calculator/invoice.html',
        {
            'pagesize': 'A4',
            'ElementsForm': Elements, 'ParametersForm':Parameters, 'calculator':calculator
        }
    )

data/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Mainbar, Category, Product, Sorter, FirstCategory, SecondCategory, ProductFilter
from cart.forms import CartAddProductForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse
from django.template.context_processors import csrf
from .forms import EmailPostForm
from django.core.mail import send_mail



def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Product, id=post_id)
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{} ({}) recommends you reading "{}"'.format(cd['name'], cd['email'], post.name)
            message = 'Read "{}" at {}\n\n{}\'s comments: {}'.format(post.name, post_url, cd['name'], cd['comments'])
            send_mail(subject, message, 'ugeopolimer@gmail.com',[cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})




def shop(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'index.html', response)

def test(request):
    response = {}
    response.update(csrf(request))
    response['bar'] = Mainbar.objects.all()
    response['mobar'] = Mainbar.objects.filter(mobile=True)
    return render(request, 'test.html', response)

def product_list(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        try:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
        except:
            pass
    return render(request,
                  'shop/product/testlist.html',
                  {'category': category,'bar':bar,'mobar':mobar,
                   'categories': categories,'sorter':sorter,
                   'products': products})

def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def product(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/product.html',
                  {'product': product, 'cart_product_form': cart_product_form})

def first(request, category_slug=None):
    category = None
    cart_product_form = CartAddProductForm()
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    if category_slug:
        category = get_object_or_404(FirstCategory, slug=category_slug)
        second = SecondCategory.objects.filter(secondcategory=category)
        products = Product.objects.filter(available=True).filter(thirdcategory=second[0])
        for item in second:
            products |= Product.objects.filter(available=True).filter(thirdcategory=item)

    return render(request,
                  'shop/product/first.html',
                  {'category': category, 'cart_product_form': cart_product_form,
                   'categories': categories,
                   'firstproducts': products,
                  'sorter':sorter})



def second(request, category_slug=None, firstcategory_slug= None, secondcategory_slug=None):
    bar = Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None

    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)
    secondcategories = SecondCategory.objects.all()
    # if firstcategory_slug:
    #     secondcategories = SecondCategory.objects.filter(secondcategory=get_object_or_404(FirstCategory, slug=firstcategory_slug))
    #     print(secondcategories)

    if secondcategory_slug:
        category = get_object_or_404(SecondCategory, slug=secondcategory_slug)
        products = products.filter(thirdcategory=category)
        category = get_object_or_404(Category, slug=category_slug)
    else:
        if category_slug:
            category = get_object_or_404(Category, slug=category_slug)
            products = products.filter(category=category)
    firstcategories=FirstCategory.objects.filter(firstcategory=get_object_or_404(Category, slug=category_slug))
    # page = request.GET.get('page')

    t=3
    fproduct = ProductFilter(request.GET, queryset=products)
    paginator = Paginator(fproduct.qs, t)  # 6 posts in each page
    page = request.GET.get('page')
    filterrequest=request.GET
    filterrequest._mutable = True
    print(filterrequest)

    if page:
        del filterrequest['page']
        lqty = int(page)*t
        uqty = int(page) * t+t
    else:
        lqty=1
        uqty=1*t

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    print(filterrequest.get('lqty'))
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category, 'bar': bar, 'mobar': mobar, 'page': page, 'filter': fproduct,'filterrequest':filterrequest,'lqty':lqty, 'uqty' :uqty,
                   'categories': categories, 'sorter': sorter, 'firstcategories':firstcategories,  'opencategory':firstcategory_slug,
                   'products': products})



def shop_sidebar(request, category_slug=None):
    bar= Mainbar.objects.all()
    mobar = Mainbar.objects.filter(mobile=True)
    category = None
    categories = Category.objects.all()
    sorter = Sorter.objects.all()
    products = Product.objects.filter(available=True)


    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    paginator = Paginator(products, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)
    f = ProductFilter(request.GET, queryset=Product.objects.all())
    return render(request,
                  'shop/product/shop-sidebar.html',
                  {'category': category,'bar':bar,'mobar':mobar,'page': page, 'filter': f,
                   'categories': categories,'sorter':sorter,
                   'products': products})

data/templates/calculator/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>


<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'assets/stylesheets/bootstrap.min.css' %}"
 <link rel="stylesheet" href="{% static 'assets/stylesheets/bootstrap-responsive.min.css' %}"
<link rel="stylesheet" href="{% static 'assets/stylesheets/application.css' %}"

 <script src="{% static 'assets/javascripts/jquery-1.9.1.js' %}"></script>
 <script src="{% static 'assets/javascripts/calculator.js' %}"></script>






    {% block head %}


    {% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
        <a class="navbar-brand" href="#">Calculator</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample09">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>

          </ul>
          <form class="form-inline my-2 my-md-0">
            <input class="form-control" type="text" placeholder="Search" aria-label="Search">
          </form>
        </div>
      </nav>

<br/>
<br/>
<br/>

{% block body %}

{% endblock %}

</body>
</html>

data/templates/calculator/base1.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <script type="text/javascript" src="{% static 'bootstrap/js/jquery.js'%}"></script>
    <link href="{% static 'bootstrap/css/bootstrap.css'%}" rel="stylesheet">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js'%}"></script>
    <style type="text/css">
        #main-conteiter {
            padding-top: 5%;
        }
    </style>
    {% block head %}
        <title>{% block title %}Example Wizard{% endblock %}</title>
    {% endblock %}
</head>

<body>
<div class="container" id="main-conteiner">
{% block content %}
    <!-- body -->
{% endblock %}
</div>

</body>
</html>

data/templates/calculator/contract.html
{% extends "calculator/wizard_template.html" %}

{% block title_wizard %}
    Контракт студента
{% endblock %}
{% block form_wizard %}
    {% if ok == 'True' %}
        <div class="alert alert-success">
            <button type="button" class="close" data-dismiss="alert">×</button>
            <strong>Отлично!</strong>
            Форма добавления ФИО студента верно заполнена.
        </div>
    {% endif %}
    {% include "calculator/input_field.html" with f=wizard.form.num1 %}
    {% include "calculator/input_field.html" with f=wizard.form.num2 %}
{% endblock %}
{% block button_wizard %}
    <button name="wizard_goto_step" class="btn btn-primary" type="submit" value="{{ wizard.steps.prev }}">
        <i class="icon-user icon-white"></i> ФИО студента <i class="icon-arrow-left icon-white"></i>
    </button>
    <input type="submit" class="btn btn-primary" value="Сохранить"/>
{% endblock %}

data/templates/calculator/home.html
{% extends 'calculator/base.html' %}
{% load static %}

{% block head %}

   <link rel="stylesheet" href="{% static 'assets/stylesheets/bootstrap.min.css' %}"
 <link rel="stylesheet" href="{% static 'assets/stylesheets/bootstrap-responsive.min.css' %}"
<link rel="stylesheet" href="{% static 'assets/stylesheets/application.css' %}"

 <script src="{% static 'assets/javascripts/jquery-1.9.1.js' %}"></script>
 <script src="{% static 'assets/javascripts/calculator.js' %}"></script>
{% endblock %}


{% block body %}

  <div class="container text-center">

    <h1>Calculator</h1>
      <br/>
      <br/>


      <form action="" method="post">
          {% csrf_token %}
          {{ form.as_p }}



          <button type="submit" name="add">ADD</button>
          <button type="submit" name="sub">SUB</button>
          <button type="submit" name="mul">MUL</button>
          <button type="submit" name="div">DIV</button>



      </form>

      <br/>
      <br/>
       <h3>Result:  {{ result }}</h3>


  <div class="hero-unit" id="calculator-wrapper">
       <div class="row-fluid">
        <div class="span8">
           <div id="calculator-screen" class="uneditable-input"></div>
         </div>
          <div class="span1" style="text-align: center;">
           <div class="visible-phone">
             =
           </div>
            <div class="hidden-phone">
          
            </div>
         </div>
          <div class="span3">
            <div id="calculator-result"  class="uneditable-input">0</div>
         </div>
       </div>

      </div>

      <div class="row-fluid">

        <div class="span10 well">
          <div id="calc-board">
            <div class="row-fluid">
              <a href="#" class="btn" data-constant="SIN" data-key="115">sin</a>
              <a href="#" class="btn" data-constant="COS" data-key="99">cos</a>
              <a href="#" class="btn" data-constant="MOD" data-key="109">md</a>
              <a href="#" class="btn btn-danger" data-method="reset" data-key="8">C</a>
            </div>
            <div class="row-fluid">
              <a href="#" class="btn" data-key="55">7</a>
              <a href="#" class="btn" data-key="56">8</a>
              <a href="#" class="btn" data-key="57">9</a>
              <a href="#" class="btn" data-constant="BRO" data-key="40">(</a>
              <a href="#" class="btn" data-constant="BRC" data-key="41">)</a>
            </div>
            <div class="row-fluid">
              <a href="#" class="btn" data-key="52">4</a>
              <a href="#" class="btn" data-key="53">5</a>
              <a href="#" class="btn" data-key="54">6</a>
              <a href="#" class="btn" data-constant="MIN" data-key="45">-</a>
              <a href="#" class="btn" data-constant="SUM" data-key="43">+</a>
            </div>
            <div class="row-fluid">
              <a href="#" class="btn" data-key="49">1</a>
              <a href="#" class="btn" data-key="50">2</a>
              <a href="#" class="btn" data-key="51">3</a>
              <a href="#" class="btn" data-constant="DIV" data-key="47">/</a>
              <a href="#" class="btn" data-constant="MULT" data-key="42">*</a>
            </div>
            <div class="row-fluid">
              <a href="#" class="btn" data-key="46">.</a>
              <a href="#" class="btn" data-key="48">0</a>
              <a href="#" class="btn" data-constant="PROC" data-key="37">%</a>
              <a href="#" class="btn btn-primary" data-method="calculate" data-key="61">=</a>
            </div>
          </div>
        </div>

        <div class="span6 well">
          <legend>History</legend>
          <div id="calc-panel">
            <div id="calc-history">
              <ol id="calc-history-list"></ol>
            </div>
          </div>
        </div>
        <hr>

      </div>
    </div>



{% endblock %}

data/templates/calculator/input_field.html
<div class="control-group {% if f.errors %}error{% endif %}">
    <label class="control-label" for="{{f.id_for_label}}">{{ f.label|capfirst }}</label>
    <div class="controls">
        {{f}}
        <span class="help-inline">
            {% for error in f.errors %}
                {{ error|escape }}
            {% endfor %}
        </span>
    </div>
</div>

data/templates/calculator/invoice.html
{% extends 'head.html' %}
{% load static %}
{% block index %}

    <!-- Body main wrapper start -->


            <form method="get" >
                {{ ElementsForm.as_table }}
                {% csrf_token %}

                <input type="submit" value="Показать расписание">

             </form>
    <div class="container">
        <div class="table-content table-responsive">

            <table>
                <thead>
                    <tr>
                        <th>Element</th>
                        <th>Form</th>
                        <th><a href='/calculator/test/'>Calculate</a></th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>


                {% for element in calculator.main.values %}
                <form method="get" >
                {% for el in ParametersForm %}



                {% if forloop.counter == 1  %}

                <tr class="cart-subtotal">
                    <td rowspan="{{forloop.revcounter}}">{{element.name}}<input type="text" value="{{element.id}}" name="quantity"></td>
                    <th>{{el}} </th>
                    <th rowspan="{{forloop.revcounter}}" ><a href='{% url "calculator:calculator_remove"  id="main" element_id=element.id%}'><input type="submit" value="Показать расписание" name="print_btn"></a></th>
                    <td rowspan="{{forloop.revcounter}}" class="product-remove"><a href='{% url "calculator:calculator_remove"  id="main" element_id=element.id%}'>X</a></td>
                </tr>
                    {% else %}
                <tr class="cart-subtotal">
                         <th> {{el}}</th>
                </tr>
                {% endif %}
                {% endfor %}
                    </form>

                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
<div class="container">
<div class="table-content table-responsive">

            <table>
                <thead>
                    <tr>
                        <th>Process</th>
                        <th>Productivity</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody>

                {% for process, productivity in calculator.process.items %}
                <tr class="cart-subtotal">
                    <td>{{ process}} </td>
                    <td>{{ productivity.hours }}</td>
                    <td class="product-remove"><a href='{% url "calculator:calculator_remove"  id="process" element_id=productivity.id.id %}'>X</a></td>

               </tr>{% endfor %}
                </tbody>

            </table></div></div>
<div class="container">
<div class="table-content table-responsive">

            <table>
                <thead>
                    <tr>
                        <th class="product-thumbnail">Image</th>
                        <th class="product-name">Material</th>
                        <th class="product-price">Price</th>
                        <th class="product-quantity">Quantity</th>
                        <th class="product-subtotal">Total</th>
                        <th class="product-remove">Remove</th>
                    </tr>
                </thead>
                <tbody>

                {% for item in calculator.norms.items %}
                <tr class="cart-subtotal">
                    <td class="product-thumbnail">
                        <a href="#">
                            <img src="
                                {% if item.1.materials.image %}
                                    {{ item.1.materials.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                     </td>
                    <td class="product-name"><a href="#">{{ item.1.materials.name  }}</a></td>
                    <td class="product-price"><span class="amount">${{ item.1.materials.price }}</span></td>
                    <td class="product-quantity"><input type="number" value= {{ item.1.quantity}} /></td>
                    <td class="product-subtotal">${{ item.1.total}}</td>
                    <td class="product-remove"><a href='{% url "calculator:calculator_remove"  id="product" element_id=item.1.materials.id %}'>X</a></td>



                </tr>{% endfor %}

                </tbody>

            </table></div></div>

   {% endblock %}

data/templates/calculator/student.html
{% extends "calculator/wizard_template.html" %}
{% load i18n %}
{% block title_wizard %}
    Добавление студета
{% endblock %}
{% block form_wizard %}
    {% include "calculator/input_field.html" with f=wizard.form.quantity %}

{% endblock %}
{% block button_wizard %}
    <button type="submit" class="btn btn-primary">
        <i class="icon-user icon-white"></i> Контракт <i class="icon-arrow-right icon-white"></i>
    </button>
{% endblock %}

data/templates/calculator/wizard_template.html
{% extends "calculator/base1.html" %}
{% block head %}
    {{ block.super }}
    {{ wizard.form.media }}
{% endblock %}
{% block content %}
    <p class="text-info">Создание студента, шаг {{ wizard.steps.step1 }} из {{ wizard.steps.count }}</p>
    <h3>{% block title_wizard %}{% endblock %}</h3>
    <form class="well form-horizontal" action="." method="POST">{% csrf_token  %}
        {{ wizard.management_form }}
        <div class="control-group">
          {% block form_wizard %}

          {% endblock %}
        </div>
        <div class="form-actions" style="padding-left: 50%">
            {% block button_wizard %}

            {% endblock %}
        </div>
    </form>
{% endblock %}